#!/bin/sh

cdebootstrap-static --allow-unauthenticated --include=openssh-server --arch=armhf wheezy /rootfs http://mirrordirector.raspbian.org/raspbian/

# allow root login
echo -n root:raspbian | chroot /rootfs /usr/sbin/chpasswd

# default mounts
echo "/dev/mmcblk0p1 /boot vfat defaults 0 0" > /rootfs/etc/fstab
echo "/dev/mmcblk0p2 / ext4 errors=remount-ro,noatime 0 0" >> /rootfs/etc/fstab

# default hostname
echo -n pi > /rootfs/etc/hostname
echo "127.0.0.1 localhost pi" > /rootfs/etc/hosts

# dhcp networking
echo "auto lo" > /rootfs/etc/network/interfaces
echo "iface lo inet loopback" >> /rootfs/etc/network/interfaces
echo "auto eth0" >> /rootfs/etc/network/interfaces
echo "iface eth0 inet dhcp" >> /rootfs/etc/network/interfaces
