#!/bin/busybox sh

mkdir -p /proc
mkdir -p /sys
mkdir -p /usr/bin
mkdir -p /usr/sbin
mkdir -p /var/run
mkdir -p /rootfs/boot
mkdir -p /bootfs

/bin/busybox --install

export PATH=/bin:/sbin:/usr/bin

mount -t proc none /proc
mount -t sysfs none /sys

echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s

klogd -c 1

echo "==========================================="
echo " Welcome to automatic Raspbian installer!  "
echo "==========================================="
echo " Revision __VERSION__"
echo " Built on __DATE__"
echo "http://github.com/hifi/raspbian-ua-netinst/"
echo "==========================================="

echo -n "Waiting for eth0... "

for i in `seq 1 10`; do

    ifconfig eth0 &>/dev/null
    if [ $? -eq 0 ]; then
        echo "OK"
        break
    fi

    if [ $i -eq 10 ]; then
        echo "FAILED"
        exit
    fi

    sleep 1

    echo -n "$i.. "
done

echo -n "Configuring eth0 with DHCP... "

udhcpc -i eth0 &>/dev/null
if [ $? -eq 0 ]; then
    ifconfig eth0 | fgrep addr: | awk '{print $2}' | cut -d: -f2
else
    echo "FAILED"
    exit
fi

echo -n "Saving boot files... "
# copy boot data to safety if not fetching them
mount /dev/mmcblk0p1 /boot || exit
cp /boot/* /bootfs/ || exit
umount /boot || exit
echo "OK"

echo -n "Applying new partition table... "
dd if=/dev/zero of=/dev/mmcblk0 bs=512 count=1 &>/dev/null
fdisk /dev/mmcblk0 &>/dev/null <<EOF
n
p
1

+50M
t
b
n
p
2


w
EOF
echo "OK"

echo -n "Initializing /boot as vfat... "
mkfs.vfat /dev/mmcblk0p1 &>/dev/null || exit
echo "OK"

echo -n "Initializing / as ext4... "
mkfs.ext4 /dev/mmcblk0p2 &>/dev/null || exit
echo "OK"

echo -n "Mounting new filesystems... "
mount /dev/mmcblk0p2 /rootfs || exit
mkdir /rootfs/boot || exit
mount /dev/mmcblk0p1 /rootfs/boot || exit
echo "OK"

echo -n "Copying /boot files in... "
cp /bootfs/* /rootfs/boot || exit
sync
echo "OK"

echo "Starting install process..."
. /sbin/install

echo "Configuring bootloader to start the installed system..."
mv /rootfs/boot/config.txt /rootfs/boot/config-reinstall.txt

echo "Unmounting filesystems..."
umount /rootfs/boot
umount /rootfs

echo "Finished! Rebooting to installed system."
reboot
