#!/bin/busybox sh

# default options, can be overriden in installer-config.txt
preset=server
packages=
mirror=http://mirrordirector.raspbian.org/raspbian/
release=wheezy
hostname=pi
rootpw=raspbian
cdebootstrap_cmdline=
bootsize=+50M
rootsize=
timeserver=time.nist.gov
ip_addr=dhcp
ip_netmask=0.0.0.0
ip_broadcast=0.0.0.0
ip_gateway=0.0.0.0
ip_nameservers=
online_config=
usbroot=
cmdline="dwc_otg.lpm_enable=0 console=ttyAMA0,115200 kgdboc=ttyAMA0,115200 console=tty1 elevator=deadline"
rootfstype=ext4

# these shouldn't really be changed unless auto-detection fails
bootdev=/dev/mmcblk0
bootpartition=/dev/mmcblk0p1
rootdev=/dev/mmcblk0
rootpartition=

fail()
{
    echo
    echo "Oh noes, something went wrong!"
    echo "You have 10 seconds to hit ENTER to get a shell..."

    read -t 10 || reboot && exit
    sh
}

mkdir -p /proc
mkdir -p /sys
mkdir -p /boot
mkdir -p /usr/bin
mkdir -p /usr/sbin
mkdir -p /var/run
mkdir -p /rootfs/boot
mkdir -p /bootfs

/bin/busybox --install

export PATH=/bin:/sbin:/usr/bin

mount -t proc none /proc
mount -t sysfs none /sys

echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s

klogd -c 1

echo "==========================================="
echo "raspbian-ua-netinst"
echo "==========================================="
echo "Revision __VERSION__"
echo "Built on __DATE__"
echo "==========================================="
echo "http://github.com/hifi/raspbian-ua-netinst/"
echo "==========================================="

echo -n "Copying boot files... "
# copy boot data to safety
mount $bootpartition /boot || fail

cp /boot/bootcode.bin \
    /boot/fixup_cd.dat \
    /boot/fixup.dat \
    /boot/fixup_x.dat \
    /boot/installer.cpio \
    /boot/kernel_install.img \
    /boot/start_cd.elf \
    /boot/start.elf \
    /boot/start_x.elf /bootfs/ || fail

# use install kernel in first boot
cp /boot/kernel_install.img /bootfs/kernel.img || fail

if [ -f /boot/installer-config.txt ]; then
    cp /boot/installer-config.txt /bootfs/installer-config.txt || fail
fi

if [ -f /boot/post-install.txt ]; then
    cp /boot/post-install.txt /bootfs/post-install.txt || fail
fi

# if installation aborts it will restart
cp /boot/config.txt /bootfs/config.txt || fail

umount /boot || fail
echo "OK"

if [ -e /bootfs/installer-config.txt ]; then
    echo "Reading installer-config.txt..."
    source /bootfs/installer-config.txt
fi

case "$rootfstype" in
  "btrfs")
    kernel_module=true
    rootfs_mkfs_options=${rootfs_mkfs_options:-'-f'}
    rootfs_install_mount_options=${rootfs_install_mount_options:-'noatime'}
    rootfs_mount_options=${rootfs_mount_options:-'noatime'}
    ;;
  "ext4")
    kernel_module=false
    rootfs_mkfs_options=${rootfs_mkfs_options:-''}
    rootfs_install_mount_options=${rootfs_install_mount_options:-'noatime,data=writeback,nobarrier,noinit_itable'}
    rootfs_mount_options=${rootfs_mount_options:-'errors=remount-ro,noatime'}
    ;;
  "f2fs")
    kernel_module=true
    rootfs_mkfs_options=${rootfs_mkfs_options:-''}
    rootfs_install_mount_options=${rootfs_install_mount_options:-'noatime'}
    rootfs_mount_options=${rootfs_mount_options:-'errors=remount-ro,noatime'}
    ;;
esac

echo
echo "Network configuration:"
echo "  ip_addr = $ip_addr"

if [ "$ip_addr" != "dhcp" ]; then
    echo "  ip_netmask = $ip_netmask"
    echo "  ip_broadcast = $ip_broadcast"
    echo "  ip_gateway = $ip_gateway"
    echo "  ip_nameservers = $ip_nameservers"
fi

echo "  online_config = $online_config"
echo

echo -n "Waiting for eth0... "

for i in `seq 1 10`; do

    ifconfig eth0 &>/dev/null
    if [ $? -eq 0 ]; then
        echo "OK"
        break
    fi

    if [ $i -eq 10 ]; then
        echo "FAILED"
        fail
    fi

    sleep 1

    echo -n "$i.. "
done

if [ "$ip_addr" = "dhcp" ]; then
    echo -n "Configuring eth0 with DHCP... "

    udhcpc -i eth0 &>/dev/null
    if [ $? -eq 0 ]; then
        ifconfig eth0 | fgrep addr: | awk '{print $2}' | cut -d: -f2
    else
        echo "FAILED"
        fail
    fi
else
    echo -n "Configuring eth0 with static ip $ip_addr... "
    ifconfig eth0 up inet $ip_addr netmask $ip_netmask broadcast $ip_broadcast || fail
    route add default gw $ip_gateway || fail
    echo -n > /etc/resolv.conf
    for i in $ip_nameservers; do
        echo "nameserver $i" >> /etc/resolv.conf
    done
    echo "OK"
fi

if [ "$online_config" != "" ]; then
    echo -n "Downloading online config from $online_config... "
    wget -q -O /online-config.txt $online_config &>/dev/null || fail
    echo "OK"

    echo "Reading online-config.txt..."
    source /online-config.txt
fi

# configure different kinds of presets
if [ "$cdebootstrap_cmdline" = "" ]; then

    # minimal
    cdebootstrap_cmdline="--flavour=minimal --include=kmod,fake-hwclock,ifupdown,net-tools,ntp,openssh-server$dhcp_packages"

    # add dhcp client if using dhcp
    if [ "$ip_addr" = "dhcp" ]; then
        cdebootstrap_cmdline="$cdebootstrap_cmdline,isc-dhcp-client"
    fi

    case $preset in
        minimal)
            ;;
        base)
            cdebootstrap_cmdline="--flavour=minimal"
            ;;
        *)
            cdebootstrap_cmdline="$cdebootstrap_cmdline,vim-tiny,iputils-ping,wget,ca-certificates,rsyslog,cron,dialog,locales,less,man-db,linux-image-rpi-rpfv,raspberrypi-bootloader-nokernel"
            preset=server
            ;;
    esac

    # add extra packages
    if [ "$packages" != "" ]; then
        if [ "$preset" = "base" ]; then
            cdebootstrap_cmdline="$cdebootstrap_cmdline --include=$packages"
        else
            cdebootstrap_cmdline="$cdebootstrap_cmdline,$packages"
        fi
    fi

else
    preset=none
fi

if [ "$usbroot" != "" ]; then
    rootdev=/dev/sda
fi

if [ "$rootpartition" = "" ]; then
    if [ "$rootdev" = "/dev/sda" ]; then
        rootpartition=/dev/sda1
    else
        rootpartition=/dev/mmcblk0p2
    fi
fi

echo
echo "Installer configuration:"
echo "  preset = $preset"
echo "  packages = $packages"
echo "  mirror = $mirror"
echo "  release = $release"
echo "  hostname = $hostname"
echo "  rootpw = $rootpw"
echo "  cdebootstrap_cmdline = $cdebootstrap_cmdline"
echo "  bootsize = $bootsize"
echo "  rootsize = $rootsize"
echo "  timeserver = $timeserver"
echo "  cmdline = $cmdline"
echo "  usbroot = $usbroot"
echo "  rootdev = $rootdev"
echo "  rootpartition = $rootpartition"
echo "  rootfstype = $rootfstype"
echo "  rootfs_mkfs_options = $rootfs_mkfs_options"
echo "  rootfs_install_mount_options = $rootfs_install_mount_options"
echo "  rootfs_mount_options = $rootfs_mount_options"
echo

if [ "$timeserver" != "" ]; then
    echo -n "Configuring the clock using rdate... "
    rdate $timeserver &>/dev/null
    if [ $? -eq 0 ]; then
        date
    else
        echo "failed (not fatal)"
    fi
fi

echo -n "Waiting for $rootdev... "
for i in `seq 1 10`; do

    if [ "`fdisk -l $rootdev 2>&1 | fgrep Disk`" != "" ]; then
        echo "OK"
        break
    fi

    if [ $i -eq 10 ]; then
        echo "FAILED"
        fail
    fi

    sleep 1

    echo -n "$i.. "
done

if [ "$rootdev" = "$bootdev" ]; then
    echo -n "Applying new partition table... "
    dd if=/dev/zero of=$bootdev bs=512 count=1 &>/dev/null
    fdisk $bootdev &>/dev/null <<EOF
n
p
1

$bootsize
t
b
n
p
2

$rootsize
w
EOF
    echo "OK"
else
    echo -n "Applying new partition table for $bootdev... "
    dd if=/dev/zero of=$bootdev bs=512 count=1 &>/dev/null
    fdisk $bootdev &>/dev/null <<EOF
n
p
1

$bootsize
t
b
w
EOF
    echo "OK"

    echo -n "Applying new partition table for $rootdev... "
    dd if=/dev/zero of=$rootdev bs=512 count=1 &>/dev/null
    fdisk $rootdev &>/dev/null <<EOF
n
p
1

$rootsize
w
EOF
    echo "OK"

fi

echo -n "Initializing /boot as vfat... "
mkfs.vfat $bootpartition &>/dev/null || fail
echo "OK"

if [ "$kernel_module" == true ] ; then
  echo -n "Loading $rootfstype module..."
  modprobe $rootfstype &> /dev/null || fail
  echo "OK"
fi

echo -n "Initializing / as $rootfstype... "
mkfs.$rootfstype $rootfs_mkfs_options $rootpartition &>/dev/null || fail
echo "OK"

echo -n "Mounting new filesystems... "
mount $rootpartition /rootfs -o $rootfs_install_mount_options || fail
mkdir /rootfs/boot || fail
mount $bootpartition /rootfs/boot || fail
echo "OK"

echo -n "Copying /boot files in... "
cp /bootfs/* /rootfs/boot || fail
sync
echo "OK"

if [ "$rootfstype" = "f2fs" ] ; then
  mkdir -p /rootfs/etc/initramfs-tools
  echo "f2fs" >> /rootfs/etc/initramfs-tools/modules
elif [ "$rootfstype" = "btrfs" ] ; then
  mkdir -p /rootfs/etc/initramfs-tools
  echo "btrfs" >> /rootfs/etc/initramfs-tools/modules
fi

echo "Starting install process..."
cdebootstrap-static --arch=armhf --allow-unauthenticated $cdebootstrap_cmdline $release /rootfs $mirror || fail

# install latest kernel in /boot
echo -n "Install new kernel..."
cp -a /rootfs/vmlinuz /rootfs/boot/kernel.img

# allow root login
echo -n "Configuring installed system... "
echo -n root:$rootpw | chroot /rootfs /usr/sbin/chpasswd || fail

# default mounts
echo "$bootpartition /boot vfat defaults 0 0" > /rootfs/etc/fstab || fail
echo "$rootpartition / $rootfstype $rootfs_mount_options 0 0" >> /rootfs/etc/fstab || fail

# use ram tmpfs by default
echo "RAMTMP=yes" >> /rootfs/etc/default/tmpfs 

# default hostname
echo -n $hostname > /rootfs/etc/hostname || fail
echo "127.0.0.1 localhost $hostname" > /rootfs/etc/hosts || fail

# networking
echo "auto lo" > /rootfs/etc/network/interfaces || fail
echo "iface lo inet loopback" >> /rootfs/etc/network/interfaces || fail

# eth0 config
echo "auto eth0" >> /rootfs/etc/network/interfaces || fail
if [ "$ip_addr" = "dhcp" ]; then
    echo "iface eth0 inet dhcp" >> /rootfs/etc/network/interfaces || fail
else
    echo "iface eth0 inet static" >> /rootfs/etc/network/interfaces || fail
    echo "    address $ip_addr" >> /rootfs/etc/network/interfaces || fail
    echo "    netmask $ip_netmask" >> /rootfs/etc/network/interfaces || fail
    echo "    broadcast $ip_broadcast" >> /rootfs/etc/network/interfaces || fail
    echo "    gateway $ip_gateway" >> /rootfs/etc/network/interfaces || fail

    cp /etc/resolv.conf /rootfs/etc/ || fail
fi

# there is no hw clock on rpi
echo "HWCLOCKACCESS=no" >> /rootfs/etc/default/hwclock || fail

echo "Configuring bootloader to start the installed system..."
mv /rootfs/boot/config.txt /rootfs/boot/config-reinstall.txt

# remove cdebootstrap-helper-rc.d which prevents rc.d scripts from running
echo -n "Removing cdebootstrap-helper-rc.d... " 
chroot /rootfs /usr/bin/dpkg -r cdebootstrap-helper-rc.d &>/dev/null || fail
echo "OK"

# add firmware to default apt sources
echo -n "Configuring apt... "
echo "deb http://mirrordirector.raspbian.org/raspbian $release main firmware" > /rootfs/etc/apt/sources.list
echo "deb http://archive.raspberrypi.org/debian $release main" >> /rootfs/etc/apt/sources.list
wget -q -O - http://archive.raspberrypi.org/debian/raspberrypi.gpg.key | chroot /rootfs /usr/bin/apt-key add - &>/dev/null
echo "OK"

# add reasonable default modules, works only after kernel is properly installed
echo "snd-bcm2835" >> /rootfs/etc/modules

# default cmdline.txt
echo "Creating default cmdline.txt..."
echo "$cmdline root=$rootpartition rootfstype=$rootfstype rootwait" > /rootfs/boot/cmdline.txt

# Use initramfs
echo "Creating default config.txt..."
echo "initramfs initrd.img-3.10-3-rpi" > /rootfs/boot/config.txt

# run post install script if exists
if [ -e /bootfs/post-install.txt ]; then
    echo "Running post-install.txt..."
    source /bootfs/post-install.txt
fi

# save current time if fake-hwclock
echo "Saving current time for fake-hwclock..."
sync # synchronize before saving time to make it "more accurate"
date +"%Y-%m-%d %H:%M:%S" > /rootfs/etc/fake-hwclock.data

echo "Unmounting filesystems..."
umount /rootfs/boot
umount /rootfs

echo "Finished! Rebooting to installed system."
reboot
