#!/bin/sh
#
# The base for this file came from
# /usr/share/doc/initramfs-tools-core/examples/example_hook

# List the soft prerequisites here.  This is a space separated list of
# names, of scripts that are in the same directory as this one, that
# must be run before this one can be.
#
PREREQ=""

prereqs()
{
        echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
        prereqs
        exit 0
        ;;
esac

# Source the 'hook-functions' scriptlet to use the functions defined
# within it.
. /usr/share/initramfs-tools/hook-functions


# Include fsck.fat into the initramfs
if command -v fsck.fat >/dev/null 2>&1; then
        copy_exec /sbin/fsck.fat /sbin/ 
fi

exit 0
